name: Table QA with Playwright

on: [push]

jobs:
  run-scraper:
    name: Run-Playwright-QA-email-24f2001830@ds.study.iitm.ac.in
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Deps
        run: |
          pip install playwright
          playwright install chromium

      - name: Run Sum Script
        run: python sum_tables.py
